#############################################################################
# Makefile for building: ShinPlayer
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  qt_port.pro
# Template: app
# Command: C:\Qt\QtStatic\5.12.12\bin\qmake.exe -o Makefile qt_port.pro -spec win32-msvc
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\QtStatic\5.12.12\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\QtStatic\5.12.12\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\QtStatic\5.12.12\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: qt_port.pro C:\Qt\QtStatic\5.12.12\mkspecs\win32-msvc\qmake.conf C:\Qt\QtStatic\5.12.12\mkspecs\features\spec_pre.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\common\angle.conf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\common\windows-vulkan.conf \
		C:\Qt\QtStatic\5.12.12\mkspecs\common\msvc-desktop.conf \
		C:\Qt\QtStatic\5.12.12\mkspecs\qconfig.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_networkauth.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_networkauth_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_assimpsceneimport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_defaultgeometryloader.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfgeometryloader.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfsceneexport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfsceneimport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qdirect2d.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qgif.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qicns.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qico.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qjpeg.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qminimal.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qoffscreen.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsqlite.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsqlodbc.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsvg.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsvgicon.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtga.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtiff.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtpassthrucanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtpeakcanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtsysteccanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qttinycanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtvectorcanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtvirtualcanbus.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwbmp.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwebgl.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwebp.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwindows.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwindowsvistastyle.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qxdgdesktopportal.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_xinputgamepad.pri \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\qt_functions.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\qt_config.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\exclusive_builds.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\common\msvc-version.conf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\toolchain.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\default_pre.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\default_pre.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\resolve_config.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\default_post.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\precompile_header.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\warn_on.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\qt.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\resources.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\moc.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\opengl.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\uic.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\qmake_use.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\file_copies.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\windows.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\testcase_targets.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\exceptions.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\yacc.prf \
		C:\Qt\QtStatic\5.12.12\mkspecs\features\lex.prf \
		qt_port.pro \
		C:\Qt\QtStatic\5.12.12\plugins\styles\qwindowsvistastyle.prl \
		C:\Qt\QtStatic\5.12.12\plugins\platforms\qwindows.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qgif.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qicns.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qico.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qjpeg.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qtga.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qtiff.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qwbmp.prl \
		C:\Qt\QtStatic\5.12.12\plugins\imageformats\qwebp.prl \
		C:\Qt\QtStatic\5.12.12\lib\Qt5Widgets.prl \
		C:\Qt\QtStatic\5.12.12\lib\Qt5Gui.prl \
		C:\Qt\QtStatic\5.12.12\lib\Qt5Core.prl \
		C:\Qt\QtStatic\5.12.12\lib\qtmain.prl
	$(QMAKE) -o Makefile qt_port.pro -spec win32-msvc
C:\Qt\QtStatic\5.12.12\mkspecs\features\spec_pre.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\common\angle.conf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\common\windows-vulkan.conf:
C:\Qt\QtStatic\5.12.12\mkspecs\common\msvc-desktop.conf:
C:\Qt\QtStatic\5.12.12\mkspecs\qconfig.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_core.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_network.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_networkauth.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_networkauth_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_assimpsceneimport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_defaultgeometryloader.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfgeometryloader.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfsceneexport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_gltfsceneimport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qdirect2d.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qgenericbearer.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qgif.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qicns.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qico.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qjpeg.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qminimal.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qoffscreen.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsqlite.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsqlodbc.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsvg.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qsvgicon.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtga.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtiff.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtpassthrucanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtpeakcanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtsysteccanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qttinycanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtvectorcanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qtvirtualcanbus.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwbmp.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwebgl.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwebp.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwindows.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qwindowsvistastyle.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_qxdgdesktopportal.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\modules\qt_plugin_xinputgamepad.pri:
C:\Qt\QtStatic\5.12.12\mkspecs\features\qt_functions.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\qt_config.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\win32-msvc\qmake.conf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\QtStatic\5.12.12\mkspecs\features\exclusive_builds.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\common\msvc-version.conf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\toolchain.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\default_pre.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\default_pre.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\resolve_config.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\default_post.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\precompile_header.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\warn_on.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\qt.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\resources.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\moc.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\opengl.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\uic.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\qmake_use.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\file_copies.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\win32\windows.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\testcase_targets.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\exceptions.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\yacc.prf:
C:\Qt\QtStatic\5.12.12\mkspecs\features\lex.prf:
qt_port.pro:
C:\Qt\QtStatic\5.12.12\plugins\styles\qwindowsvistastyle.prl:
C:\Qt\QtStatic\5.12.12\plugins\platforms\qwindows.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qgif.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qicns.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qico.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qjpeg.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qtga.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qtiff.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qwbmp.prl:
C:\Qt\QtStatic\5.12.12\plugins\imageformats\qwebp.prl:
C:\Qt\QtStatic\5.12.12\lib\Qt5Widgets.prl:
C:\Qt\QtStatic\5.12.12\lib\Qt5Gui.prl:
C:\Qt\QtStatic\5.12.12\lib\Qt5Core.prl:
C:\Qt\QtStatic\5.12.12\lib\qtmain.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt_port.pro -spec win32-msvc

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\Project\OtherProgram\ShinPlayer\ClaudeTestPlayer\shinplayer_plugin_import.cpp .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
